### ISSUE TITLE
Method getGroupInfoFromInviteLink(inviteCode) return undefined

### ISSUE THREAD

**Issue by dogcalas** [orkestral/venom#1231]
## Description
When trying to get group info from its invite link, returns undefined
```
const group = await client.getGroupInfoFromInviteLink(inviteCode)
console.log(inviteCode, group)
```

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):** 3.1.11
- **Browser:** Chrome 95.0.4638.54
- **OS:** Ubuntu
- **Node version:** 12.18.3

## Steps to Reproduce

1. Add the bot number to a group manually and get the invite link
2.  Create a client
3. Use getGroupInfoFromInviteLink with the invite link

**Comment by orkestral** [comment]
fixed in version 4.0.1

**Comment by diegodorgam** [comment]
still returning `undefined` in 4.0.2
some links throws an error `Evaluation failed: i`

anyone else got this?

**Comment by dogcalas** [comment]
On version 4.0.3 this problem persist. This issue should be reopen.

**Comment by reinaldoluckman** [comment]
On version 4.0.9 this problem persist. This issue should be reopen.
