### ISSUE TITLE
Messages object no longer shows quoted message

### ISSUE THREAD

**Issue by ProbBC** [orkestral/venom#1250]
## Description

When receiving a message, it is expected that the message object shows the "quotedMsgObj" property, to identify the replied message. It was working in previous version.

## Environment

- **Venom version(s):** 3.1.12
- **Browser:** Chrome 95.0.4638.69
- **OS:** Windows 10
- **Node version:** 16.2.0

## Steps to Reproduce

1. Receive a message with onMessage or onAnyMessage event

**Comment by lucianodltec** [comment]
Having same problem here... it´s quite simple to reproduce.

**Comment by orkestral** [comment]
fixed in version 4.0.1

**Comment by ProbBC** [comment]
the "quotedMsgObj" property is still missing from the messages in version 4.0.1, how can i get it?

**Comment by lucianodltec** [comment]
Just updated to 4.0.1 and "quotedMsg" attribute still missing on message object.
Any news on that?
