### ISSUE TITLE
Error: message is missing critical data neeeded to download the file

### ISSUE THREAD

**Issue by noire-xv** [orkestral/venom#603]
## Description

I'm trying to decrypt message and I got this error :(

## Environment

- **Venom version(s):** 2.2.4
- **Browser:** Chrome  88.0.4324.150
- **OS:** Windows Server 2016
- **Node version:** Node 14.15

## My Code

```
        const buffer = await  client.decryptFile(message);
        let base64data = Buffer.from(buffer).toString('base64');
        const imagebase64 = 'data:' + message.mimetype + ';base64,' + base64data;    
        ext = mime.extension(message.mimetype);
        var now = new Date();   
        var  fileName = "file" + now.getSeconds() + "." + ext;
        await fs.writeFileSync(`./${fileName}`, buffer);   
```

##Screenshot
![err](https://user-images.githubusercontent.com/43586004/108112495-c2dd8680-70c8-11eb-8400-5a12586c0d90.PNG)

**Comment by clovisdanielss** [comment]
Try this:

                let buffer: any = null;
                await client.decryptFile(message)
                    .then(result => buffer = result)
                    .catch(err => console.log(err));
                const fileName = `static/${anyFileName}.${mime.extension(message.mimetype)}`;
                await fs.writeFileSync(fileName, buffer);

**Comment by noire-xv** [comment]
> Try this:
> 
> ```
>             let buffer: any = null;
>             await client.decryptFile(message)
>                 .then(result => buffer = result)
>                 .catch(err => console.log(err));
>             const fileName = `static/${anyFileName}.${mime.extension(message.mimetype)}`;
>             await fs.writeFileSync(fileName, buffer);
> ```

its doesnt work :'(

**Comment by clovisdanielss** [comment]
Its odd, this problem was fixed in previous [issue](https://github.com/orkestral/venom/issues/585). 

Try to clean install venom, and make sure that you're using version 2.2.4.

**Comment by noire-xv** [comment]
I've tried to clean install and my venom ver is latest version and problem still same

**Comment by sircaio21** [comment]
use "downloadMedia" rather than "decryptFile".
Example:
`const buffer = await client.downloadMedia(message);`
//this return a base64 directly

**Comment by orkestral** [comment]
corrention in npm i venom-bot version 3.0.3
