### ISSUE TITLE
ERROR : onStateChange does not catch logout event 

### ISSUE THREAD

**Issue by grupobyb** [orkestral/venom#781]
When disconnecting the session from the phone Venom-bot does not send the change of state

this happened to someone else ?

TKS

**Comment by grupobyb** [comment]
Thanks a lot !! We would like to know how to do to collaborate with this project, better understand the crawler and more

**Comment by jonalan7** [comment]
Update to new version this problem was fixed!

**Comment by grupobyb** [comment]
@jonalan7  after the update the problem was not solved, we still cannot read the status change
